### ISSUE TITLE
Unable to use GPU for model inference, and encountering division by zero issues when calculating F1 score

### ISSUE THREAD

**Issue by yinhong-hu** [yanran-tang/PromptCase#2]
When I execute the code, I've noticed that GPU cannot be used for model inference, and there is a tendency for division by zero issues when calculating the F1 score. I have already made modifications to the relevant code and submitted it for your attention.

**Comment by yanran-tang** [comment]
Thank you for your modification.

1. For the model inference, I didn't run it on GPU because my GPU memory is not enough to do the inference.
2. For the F1 score calculation, thank you for modifying it to avoid zero issues.

It would be appreciated if you could delete the GPU modification while remaining F1 score formula modification, then the pull request can be merged.

**Comment by yinhong-hu** [comment]
I have removed the code for GPU inference and kept the code modifications for calculating the F1 score.




huyinhong
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanran-tang/PromptCase"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月8日(星期天) 晚上6:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanran-tang/PromptCase] Unable to use GPU for model inference, and encountering division by zero issues when calculating F1 score (Issue #2)





 
Thank you for your modification.
  
For the model inference, I didn't run it on GPU because my GPU memory is not enough to do the inference.
 
For the F1 score calculation, thank you for modifying it to avoid zero issues.
  
It would be appreciated if you could delete the GPU modification while remaining F1 score formula modification, then the pull request can be merged.

**Comment by yanran-tang** [comment]
Thank you for your useful modification, I have merged the PR.
