### ISSUE TITLE
One question about the result

### ISSUE THREAD

**Issue by OscarHPX** [yanran-tang/PromptCase#3]
Thanks for your contribution. I used your code to do the test, but got 0 in 'Correct Predictions' as the results. What should I notice in the process of testing？
![result](https://github.com/yanran-tang/PromptCase/assets/95044006/79aceb9b-80c9-4ec0-9b9a-438a9a83d89b)

**Comment by yanran-tang** [comment]
Looks like the model is correctly predicting the relevant cases. Can you provide the details to reproduce this bug?

**Comment by OscarHPX** [comment]
> Looks like the model is correctly predicting the relevant cases. Can you provide the details to reproduce this bug?
I printed 'true_list' and 'pred_list' as figure 1. It seems that the mode predict the relevance of cases inaccurately.
![2](https://github.com/yanran-tang/PromptCase/assets/95044006/5b7cc438-e376-4362-9b85-1f97d448d669)


And to avoid the denominator goes zero, I add epsilon = 1e-8 on it.
![1](https://github.com/yanran-tang/PromptCase/assets/95044006/ac33badc-226f-45c4-b112-aa381a7c868f)

**Comment by yanran-tang** [comment]
Thank you very much for providing the details.

The bug is for the reason that the labels are in int format while the predicted cases are in str format.
1. To solve this bug, 

- I have updated the code, you can update the code for another try,

- or you can just simply add a row of code (360) as below to solve the problem:

![image](https://github.com/yanran-tang/PromptCase/assets/128961386/d3e480fe-d055-42b5-9805-fc960753886d)

2. The updated code also includes the added epsilon.

**Comment by OscarHPX** [comment]
Thanks for your rapidly replying. After adjusting the codes, most of problems have been solved. But there are still three problem on evaluation indicators which are MRR@5, MAP, NDCG@5.
![1](https://github.com/yanran-tang/PromptCase/assets/95044006/18180ab4-3bf7-4407-9222-35454b8a6c92)

So, I try to figure it out and notice that "traget_list" is all False without True. Maybe it is the reason.
![2](https://github.com/yanran-tang/PromptCase/assets/95044006/ab7fdf3c-1420-4a4f-b4df-5210304715d6)

**Comment by yanran-tang** [comment]
Thanks for your bug details. I just fixed this issue and also updated the code. Could you please update the code for another try again? 
Thank you.

**Comment by OscarHPX** [comment]
Very smoothly！!  Thanks for your excellent work. 
Greetings from distant China.

**Comment by yanran-tang** [comment]
Happy to see that!
Thank you :)
