### ISSUE TITLE
Issues about integrating into the baselines

### ISSUE THREAD

**Issue by ke-01** [yanran-tang/PromptCase#6]
Hello, I'm interested in your paper. 
I would like to know specifically how it is integrated into the baselines. 
Do you only use LLM to generate legal features, summarize the entire case text, and use it as input for the baseline? 
And how is the encoding of legal features obtained, and how is the result of the dot product calculation then integrated into the baselines?

**Comment by yanran-tang** [comment]
Hi, 
Thanks for your interest in PromptCase.
    - LLM is only used to summarize the case into legal facts. The legal issues are extracted by case preprocessing. The legal facts and legal issues will be used as the input for baselines.
    - All LM baselines are only used as the encoding tool to encode the legal features into case embeddings. To integrate into different baselines, it can be simply done by changing the SAILER model into different LM baseline models in PromptCase_model.py[https://github.com/yanran-tang/PromptCase/blob/6d1c06e6d4ebffdfba93e5222f322f9a788108e8/PromptCase_model.py#L63](url)
    - The dot product calculation of baselines remains the same for LM baselines as in the case similarity part in PromptCase_model.py[https://github.com/yanran-tang/PromptCase/blob/6d1c06e6d4ebffdfba93e5222f322f9a788108e8/PromptCase_model.py#L218](url)

**Comment by ke-01** [comment]
I understand, thank you very much for your response.

**Comment by ke-01** [comment]
I understand, thank you very much for your response.
